apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            allowPrivilegeEscalation: false
          env:
            - name: VPN_SERVICE_PROVIDER
              value: airvpn
            - name: VPN_TYPE
              value: wireguard
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: gluetun-vpn
                  key: WIREGUARD_PRIVATE_KEY
            - name: WIREGUARD_PRESHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: gluetun-vpn
                  key: WIREGUARD_PRESHARED_KEY
            - name: WIREGUARD_ADDRESSES
              value: "10.150.98.252/32"
            - name: TZ
              value: America/Los_Angeles
            - name: PUID
              value: "1000"
            - name: PGID
              value: "10"
            - name: HTTPPROXY
              value: "off"
            - name: SHADOWSOCKS
              value: "off"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "172.0.0.0/12,192.168.0.0/24,10.0.0.0/24"
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "46162"
            - name: UPDATER_PERIOD
              value: "24h"
          volumeMounts:
            - name: gluetun-config
              mountPath: /gluetun
            - name: tun-device
              mountPath: /dev/net/tun

        - name: qbittorrent
          image: linuxserver/qbittorrent:latest
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: America/Los_Angeles
            - name: WEBUI_PORT
              value: "8090"
            - name: UMASK
              value: "022"
          ports:
            - name: webui
              containerPort: 8090
              protocol: TCP
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: torrents
              mountPath: /torrents

      volumes:
        - name: tun-device
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-config
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: torrents
          persistentVolumeClaim:
            claimName: torrents
